#!/bin/sh
# -*- sh -*-
LIBDIR=/usr/local/lib/lksctp-tools
BINDIR=/usr/local/bin
export LD_PRELOAD=${LIBDIR}/libwithsctp.so.1.0.16
if ! ${BINDIR}/checksctp 2> /dev/null
then
    ${BINDIR}/checksctp;
    exit 1;
fi

exec "$@"
