// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/databasevalues/building.proto

#ifndef PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace databasevalues {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();

class Building;

// ===================================================================

class Building : public ::google::protobuf::Message {
 public:
  Building();
  virtual ~Building();

  Building(const Building& from);

  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Building& default_instance();

  void Swap(Building* other);

  // implements Message ----------------------------------------------

  Building* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Building& from);
  void MergeFrom(const Building& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional uint32 opex = 2;
  inline bool has_opex() const;
  inline void clear_opex();
  static const int kOpexFieldNumber = 2;
  inline ::google::protobuf::uint32 opex() const;
  inline void set_opex(::google::protobuf::uint32 value);

  // optional uint32 citizen_limit = 3;
  inline bool has_citizen_limit() const;
  inline void clear_citizen_limit();
  static const int kCitizenLimitFieldNumber = 3;
  inline ::google::protobuf::uint32 citizen_limit() const;
  inline void set_citizen_limit(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cmexample2domain.databasevalues.Building)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_opex();
  inline void clear_has_opex();
  inline void set_has_citizen_limit();
  inline void clear_has_citizen_limit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::uint32 opex_;
  ::google::protobuf::uint32 citizen_limit_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto();

  void InitAsDefaultInstance();
  static Building* default_instance_;
};
// ===================================================================


// ===================================================================

// Building

// optional string name = 1;
inline bool Building::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Building::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Building::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Building::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Building::name() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Building.name)
  return *name_;
}
inline void Building::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:cmexample2domain.databasevalues.Building.name)
}
inline void Building::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample2domain.databasevalues.Building.name)
}
inline void Building::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample2domain.databasevalues.Building.name)
}
inline ::std::string* Building::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:cmexample2domain.databasevalues.Building.name)
  return name_;
}
inline ::std::string* Building::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Building::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample2domain.databasevalues.Building.name)
}

// optional uint32 opex = 2;
inline bool Building::has_opex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Building::set_has_opex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Building::clear_has_opex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Building::clear_opex() {
  opex_ = 0u;
  clear_has_opex();
}
inline ::google::protobuf::uint32 Building::opex() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Building.opex)
  return opex_;
}
inline void Building::set_opex(::google::protobuf::uint32 value) {
  set_has_opex();
  opex_ = value;
  // @@protoc_insertion_point(field_set:cmexample2domain.databasevalues.Building.opex)
}

// optional uint32 citizen_limit = 3;
inline bool Building::has_citizen_limit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Building::set_has_citizen_limit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Building::clear_has_citizen_limit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Building::clear_citizen_limit() {
  citizen_limit_ = 0u;
  clear_has_citizen_limit();
}
inline ::google::protobuf::uint32 Building::citizen_limit() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Building.citizen_limit)
  return citizen_limit_;
}
inline void Building::set_citizen_limit(::google::protobuf::uint32 value) {
  set_has_citizen_limit();
  citizen_limit_ = value;
  // @@protoc_insertion_point(field_set:cmexample2domain.databasevalues.Building.citizen_limit)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample2domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fbuilding_2eproto__INCLUDED
