// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/databasevalues/citizen.proto

#ifndef PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace databasevalues {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();

class Citizen;

// ===================================================================

class Citizen : public ::google::protobuf::Message {
 public:
  Citizen();
  virtual ~Citizen();

  Citizen(const Citizen& from);

  inline Citizen& operator=(const Citizen& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Citizen& default_instance();

  void Swap(Citizen* other);

  // implements Message ----------------------------------------------

  Citizen* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Citizen& from);
  void MergeFrom(const Citizen& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 tax = 1;
  inline bool has_tax() const;
  inline void clear_tax();
  static const int kTaxFieldNumber = 1;
  inline ::google::protobuf::uint32 tax() const;
  inline void set_tax(::google::protobuf::uint32 value);

  // optional string building = 2;
  inline bool has_building() const;
  inline void clear_building();
  static const int kBuildingFieldNumber = 2;
  inline const ::std::string& building() const;
  inline void set_building(const ::std::string& value);
  inline void set_building(const char* value);
  inline void set_building(const char* value, size_t size);
  inline ::std::string* mutable_building();
  inline ::std::string* release_building();
  inline void set_allocated_building(::std::string* building);

  // @@protoc_insertion_point(class_scope:cmexample2domain.databasevalues.Citizen)
 private:
  inline void set_has_tax();
  inline void clear_has_tax();
  inline void set_has_building();
  inline void clear_has_building();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* building_;
  ::google::protobuf::uint32 tax_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto();

  void InitAsDefaultInstance();
  static Citizen* default_instance_;
};
// ===================================================================


// ===================================================================

// Citizen

// optional uint32 tax = 1;
inline bool Citizen::has_tax() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Citizen::set_has_tax() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Citizen::clear_has_tax() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Citizen::clear_tax() {
  tax_ = 0u;
  clear_has_tax();
}
inline ::google::protobuf::uint32 Citizen::tax() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Citizen.tax)
  return tax_;
}
inline void Citizen::set_tax(::google::protobuf::uint32 value) {
  set_has_tax();
  tax_ = value;
  // @@protoc_insertion_point(field_set:cmexample2domain.databasevalues.Citizen.tax)
}

// optional string building = 2;
inline bool Citizen::has_building() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Citizen::set_has_building() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Citizen::clear_has_building() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Citizen::clear_building() {
  if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_->clear();
  }
  clear_has_building();
}
inline const ::std::string& Citizen::building() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Citizen.building)
  return *building_;
}
inline void Citizen::set_building(const ::std::string& value) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(value);
  // @@protoc_insertion_point(field_set:cmexample2domain.databasevalues.Citizen.building)
}
inline void Citizen::set_building(const char* value) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample2domain.databasevalues.Citizen.building)
}
inline void Citizen::set_building(const char* value, size_t size) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample2domain.databasevalues.Citizen.building)
}
inline ::std::string* Citizen::mutable_building() {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:cmexample2domain.databasevalues.Citizen.building)
  return building_;
}
inline ::std::string* Citizen::release_building() {
  clear_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = building_;
    building_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Citizen::set_allocated_building(::std::string* building) {
  if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete building_;
  }
  if (building) {
    set_has_building();
    building_ = building;
  } else {
    clear_has_building();
    building_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample2domain.databasevalues.Citizen.building)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample2domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2fcitizen_2eproto__INCLUDED
