// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/databasevalues/infrastructure.proto

#ifndef PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "protobuf/cmexample2domain/databasevalues/building.pb.h"
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace databasevalues {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();

class Infrastructure;

// ===================================================================

class Infrastructure : public ::google::protobuf::Message {
 public:
  Infrastructure();
  virtual ~Infrastructure();

  Infrastructure(const Infrastructure& from);

  inline Infrastructure& operator=(const Infrastructure& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Infrastructure& default_instance();

  void Swap(Infrastructure* other);

  // implements Message ----------------------------------------------

  Infrastructure* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Infrastructure& from);
  void MergeFrom(const Infrastructure& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cmexample2domain.databasevalues.Building building = 1;
  inline int building_size() const;
  inline void clear_building();
  static const int kBuildingFieldNumber = 1;
  inline const ::cmexample2domain::databasevalues::Building& building(int index) const;
  inline ::cmexample2domain::databasevalues::Building* mutable_building(int index);
  inline ::cmexample2domain::databasevalues::Building* add_building();
  inline const ::google::protobuf::RepeatedPtrField< ::cmexample2domain::databasevalues::Building >&
      building() const;
  inline ::google::protobuf::RepeatedPtrField< ::cmexample2domain::databasevalues::Building >*
      mutable_building();

  // @@protoc_insertion_point(class_scope:cmexample2domain.databasevalues.Infrastructure)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cmexample2domain::databasevalues::Building > building_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto();

  void InitAsDefaultInstance();
  static Infrastructure* default_instance_;
};
// ===================================================================


// ===================================================================

// Infrastructure

// repeated .cmexample2domain.databasevalues.Building building = 1;
inline int Infrastructure::building_size() const {
  return building_.size();
}
inline void Infrastructure::clear_building() {
  building_.Clear();
}
inline const ::cmexample2domain::databasevalues::Building& Infrastructure::building(int index) const {
  // @@protoc_insertion_point(field_get:cmexample2domain.databasevalues.Infrastructure.building)
  return building_.Get(index);
}
inline ::cmexample2domain::databasevalues::Building* Infrastructure::mutable_building(int index) {
  // @@protoc_insertion_point(field_mutable:cmexample2domain.databasevalues.Infrastructure.building)
  return building_.Mutable(index);
}
inline ::cmexample2domain::databasevalues::Building* Infrastructure::add_building() {
  // @@protoc_insertion_point(field_add:cmexample2domain.databasevalues.Infrastructure.building)
  return building_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cmexample2domain::databasevalues::Building >&
Infrastructure::building() const {
  // @@protoc_insertion_point(field_list:cmexample2domain.databasevalues.Infrastructure.building)
  return building_;
}
inline ::google::protobuf::RepeatedPtrField< ::cmexample2domain::databasevalues::Building >*
Infrastructure::mutable_building() {
  // @@protoc_insertion_point(field_mutable_list:cmexample2domain.databasevalues.Infrastructure.building)
  return &building_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample2domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample2domain_2fdatabasevalues_2finfrastructure_2eproto__INCLUDED
