// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/requestinterface/readfooresponse.proto

#ifndef PROTOBUF_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "protobuf/cmexample1domain/requestinterface/foo.pb.h"
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace requestinterface {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();

class ReadFooResponse;

// ===================================================================

class ReadFooResponse : public ::google::protobuf::Message {
 public:
  ReadFooResponse();
  virtual ~ReadFooResponse();

  ReadFooResponse(const ReadFooResponse& from);

  inline ReadFooResponse& operator=(const ReadFooResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadFooResponse& default_instance();

  void Swap(ReadFooResponse* other);

  // implements Message ----------------------------------------------

  ReadFooResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadFooResponse& from);
  void MergeFrom(const ReadFooResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cmexample1domain.requestinterface.Foo foo = 1;
  inline bool has_foo() const;
  inline void clear_foo();
  static const int kFooFieldNumber = 1;
  inline const ::cmexample1domain::requestinterface::Foo& foo() const;
  inline ::cmexample1domain::requestinterface::Foo* mutable_foo();
  inline ::cmexample1domain::requestinterface::Foo* release_foo();
  inline void set_allocated_foo(::cmexample1domain::requestinterface::Foo* foo);

  // @@protoc_insertion_point(class_scope:cmexample1domain.requestinterface.ReadFooResponse)
 private:
  inline void set_has_foo();
  inline void clear_has_foo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::cmexample1domain::requestinterface::Foo* foo_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();

  void InitAsDefaultInstance();
  static ReadFooResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// ReadFooResponse

// optional .cmexample1domain.requestinterface.Foo foo = 1;
inline bool ReadFooResponse::has_foo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReadFooResponse::set_has_foo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReadFooResponse::clear_has_foo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReadFooResponse::clear_foo() {
  if (foo_ != NULL) foo_->::cmexample1domain::requestinterface::Foo::Clear();
  clear_has_foo();
}
inline const ::cmexample1domain::requestinterface::Foo& ReadFooResponse::foo() const {
  // @@protoc_insertion_point(field_get:cmexample1domain.requestinterface.ReadFooResponse.foo)
  return foo_ != NULL ? *foo_ : *default_instance_->foo_;
}
inline ::cmexample1domain::requestinterface::Foo* ReadFooResponse::mutable_foo() {
  set_has_foo();
  if (foo_ == NULL) foo_ = new ::cmexample1domain::requestinterface::Foo;
  // @@protoc_insertion_point(field_mutable:cmexample1domain.requestinterface.ReadFooResponse.foo)
  return foo_;
}
inline ::cmexample1domain::requestinterface::Foo* ReadFooResponse::release_foo() {
  clear_has_foo();
  ::cmexample1domain::requestinterface::Foo* temp = foo_;
  foo_ = NULL;
  return temp;
}
inline void ReadFooResponse::set_allocated_foo(::cmexample1domain::requestinterface::Foo* foo) {
  delete foo_;
  foo_ = foo;
  if (foo) {
    set_has_foo();
  } else {
    clear_has_foo();
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample1domain.requestinterface.ReadFooResponse.foo)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample1domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto__INCLUDED
