// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/requestinterface/readresponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample1domain/requestinterface/readresponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadResponse_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ReadResponse_Status_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample1domain/requestinterface/readresponse.proto");
  GOOGLE_CHECK(file != NULL);
  ReadResponse_descriptor_ = file->message_type(0);
  static const int ReadResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, readfooresponse_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, readalldescriptionsresponse_),
  };
  ReadResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadResponse_descriptor_,
      ReadResponse::default_instance_,
      ReadResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadResponse));
  ReadResponse_Status_descriptor_ = ReadResponse_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadResponse_descriptor_, &ReadResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto() {
  delete ReadResponse::default_instance_;
  delete ReadResponse_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::cmexample1domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfooresponse_2eproto();
  ::cmexample1domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadalldescriptionsresponse_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n=protobuf/cmexample1domain/requestinter"
    "face/readresponse.proto\022!cmexample1domai"
    "n.requestinterface\032@protobuf/cmexample1d"
    "omain/requestinterface/readfooresponse.p"
    "roto\032Lprotobuf/cmexample1domain/requesti"
    "nterface/readalldescriptionsresponse.pro"
    "to\"\321\002\n\014ReadResponse\022F\n\006status\030\001 \001(\01626.cm"
    "example1domain.requestinterface.ReadResp"
    "onse.Status\022K\n\017readFooResponse\030\002 \001(\01322.c"
    "mexample1domain.requestinterface.ReadFoo"
    "Response\022c\n\033readAllDescriptionsResponse\030"
    "\003 \001(\0132>.cmexample1domain.requestinterfac"
    "e.ReadAllDescriptionsResponse\"G\n\006Status\022"
    "\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\020\n\014INVALID_TYP"
    "E\020\002\022\021\n\rFOO_NOT_FOUND\020\003", 582);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample1domain/requestinterface/readresponse.proto", &protobuf_RegisterTypes);
  ReadResponse::default_instance_ = new ReadResponse();
  ReadResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ReadResponse_Status_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadResponse_Status_descriptor_;
}
bool ReadResponse_Status_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ReadResponse_Status ReadResponse::UNKNOWN;
const ReadResponse_Status ReadResponse::SUCCESS;
const ReadResponse_Status ReadResponse::INVALID_TYPE;
const ReadResponse_Status ReadResponse::FOO_NOT_FOUND;
const ReadResponse_Status ReadResponse::Status_MIN;
const ReadResponse_Status ReadResponse::Status_MAX;
const int ReadResponse::Status_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ReadResponse::kStatusFieldNumber;
const int ReadResponse::kReadFooResponseFieldNumber;
const int ReadResponse::kReadAllDescriptionsResponseFieldNumber;
#endif  // !_MSC_VER

ReadResponse::ReadResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample1domain.requestinterface.ReadResponse)
}

void ReadResponse::InitAsDefaultInstance() {
  readfooresponse_ = const_cast< ::cmexample1domain::requestinterface::ReadFooResponse*>(&::cmexample1domain::requestinterface::ReadFooResponse::default_instance());
  readalldescriptionsresponse_ = const_cast< ::cmexample1domain::requestinterface::ReadAllDescriptionsResponse*>(&::cmexample1domain::requestinterface::ReadAllDescriptionsResponse::default_instance());
}

ReadResponse::ReadResponse(const ReadResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample1domain.requestinterface.ReadResponse)
}

void ReadResponse::SharedCtor() {
  _cached_size_ = 0;
  status_ = 0;
  readfooresponse_ = NULL;
  readalldescriptionsresponse_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReadResponse::~ReadResponse() {
  // @@protoc_insertion_point(destructor:cmexample1domain.requestinterface.ReadResponse)
  SharedDtor();
}

void ReadResponse::SharedDtor() {
  if (this != default_instance_) {
    delete readfooresponse_;
    delete readalldescriptionsresponse_;
  }
}

void ReadResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadResponse_descriptor_;
}

const ReadResponse& ReadResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadresponse_2eproto();
  return *default_instance_;
}

ReadResponse* ReadResponse::default_instance_ = NULL;

ReadResponse* ReadResponse::New() const {
  return new ReadResponse;
}

void ReadResponse::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    status_ = 0;
    if (has_readfooresponse()) {
      if (readfooresponse_ != NULL) readfooresponse_->::cmexample1domain::requestinterface::ReadFooResponse::Clear();
    }
    if (has_readalldescriptionsresponse()) {
      if (readalldescriptionsresponse_ != NULL) readalldescriptionsresponse_->::cmexample1domain::requestinterface::ReadAllDescriptionsResponse::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample1domain.requestinterface.ReadResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .cmexample1domain.requestinterface.ReadResponse.Status status = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::cmexample1domain::requestinterface::ReadResponse_Status_IsValid(value)) {
            set_status(static_cast< ::cmexample1domain::requestinterface::ReadResponse_Status >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_readFooResponse;
        break;
      }

      // optional .cmexample1domain.requestinterface.ReadFooResponse readFooResponse = 2;
      case 2: {
        if (tag == 18) {
         parse_readFooResponse:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_readfooresponse()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_readAllDescriptionsResponse;
        break;
      }

      // optional .cmexample1domain.requestinterface.ReadAllDescriptionsResponse readAllDescriptionsResponse = 3;
      case 3: {
        if (tag == 26) {
         parse_readAllDescriptionsResponse:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_readalldescriptionsresponse()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample1domain.requestinterface.ReadResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample1domain.requestinterface.ReadResponse)
  return false;
#undef DO_
}

void ReadResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample1domain.requestinterface.ReadResponse)
  // optional .cmexample1domain.requestinterface.ReadResponse.Status status = 1;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }

  // optional .cmexample1domain.requestinterface.ReadFooResponse readFooResponse = 2;
  if (has_readfooresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->readfooresponse(), output);
  }

  // optional .cmexample1domain.requestinterface.ReadAllDescriptionsResponse readAllDescriptionsResponse = 3;
  if (has_readalldescriptionsresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->readalldescriptionsresponse(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample1domain.requestinterface.ReadResponse)
}

::google::protobuf::uint8* ReadResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample1domain.requestinterface.ReadResponse)
  // optional .cmexample1domain.requestinterface.ReadResponse.Status status = 1;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }

  // optional .cmexample1domain.requestinterface.ReadFooResponse readFooResponse = 2;
  if (has_readfooresponse()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->readfooresponse(), target);
  }

  // optional .cmexample1domain.requestinterface.ReadAllDescriptionsResponse readAllDescriptionsResponse = 3;
  if (has_readalldescriptionsresponse()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->readalldescriptionsresponse(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample1domain.requestinterface.ReadResponse)
  return target;
}

int ReadResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .cmexample1domain.requestinterface.ReadResponse.Status status = 1;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }

    // optional .cmexample1domain.requestinterface.ReadFooResponse readFooResponse = 2;
    if (has_readfooresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->readfooresponse());
    }

    // optional .cmexample1domain.requestinterface.ReadAllDescriptionsResponse readAllDescriptionsResponse = 3;
    if (has_readalldescriptionsresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->readalldescriptionsresponse());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadResponse::MergeFrom(const ReadResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_readfooresponse()) {
      mutable_readfooresponse()->::cmexample1domain::requestinterface::ReadFooResponse::MergeFrom(from.readfooresponse());
    }
    if (from.has_readalldescriptionsresponse()) {
      mutable_readalldescriptionsresponse()->::cmexample1domain::requestinterface::ReadAllDescriptionsResponse::MergeFrom(from.readalldescriptionsresponse());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadResponse::CopyFrom(const ReadResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadResponse::IsInitialized() const {

  return true;
}

void ReadResponse::Swap(ReadResponse* other) {
  if (other != this) {
    std::swap(status_, other->status_);
    std::swap(readfooresponse_, other->readfooresponse_);
    std::swap(readalldescriptionsresponse_, other->readalldescriptionsresponse_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadResponse_descriptor_;
  metadata.reflection = ReadResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample1domain

// @@protoc_insertion_point(global_scope)
