// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/requestinterface/readrequest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample1domain/requestinterface/readrequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadRequest_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ReadRequest_Type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample1domain/requestinterface/readrequest.proto");
  GOOGLE_CHECK(file != NULL);
  ReadRequest_descriptor_ = file->message_type(0);
  static const int ReadRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadRequest, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadRequest, readfoorequest_),
  };
  ReadRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadRequest_descriptor_,
      ReadRequest::default_instance_,
      ReadRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadRequest));
  ReadRequest_Type_descriptor_ = ReadRequest_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadRequest_descriptor_, &ReadRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto() {
  delete ReadRequest::default_instance_;
  delete ReadRequest_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::cmexample1domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadfoorequest_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n<protobuf/cmexample1domain/requestinter"
    "face/readrequest.proto\022!cmexample1domain"
    ".requestinterface\032\?protobuf/cmexample1do"
    "main/requestinterface/readfoorequest.pro"
    "to\"\331\001\n\013ReadRequest\022A\n\004type\030\001 \001(\01623.cmexa"
    "mple1domain.requestinterface.ReadRequest"
    ".Type\022I\n\016readFooRequest\030\002 \001(\01321.cmexampl"
    "e1domain.requestinterface.ReadFooRequest"
    "\"<\n\004Type\022\013\n\007UNKNOWN\020\000\022\014\n\010READ_FOO\020\001\022\031\n\025R"
    "EAD_ALL_DESCRIPTIONS\020\002", 382);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample1domain/requestinterface/readrequest.proto", &protobuf_RegisterTypes);
  ReadRequest::default_instance_ = new ReadRequest();
  ReadRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ReadRequest_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadRequest_Type_descriptor_;
}
bool ReadRequest_Type_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ReadRequest_Type ReadRequest::UNKNOWN;
const ReadRequest_Type ReadRequest::READ_FOO;
const ReadRequest_Type ReadRequest::READ_ALL_DESCRIPTIONS;
const ReadRequest_Type ReadRequest::Type_MIN;
const ReadRequest_Type ReadRequest::Type_MAX;
const int ReadRequest::Type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ReadRequest::kTypeFieldNumber;
const int ReadRequest::kReadFooRequestFieldNumber;
#endif  // !_MSC_VER

ReadRequest::ReadRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample1domain.requestinterface.ReadRequest)
}

void ReadRequest::InitAsDefaultInstance() {
  readfoorequest_ = const_cast< ::cmexample1domain::requestinterface::ReadFooRequest*>(&::cmexample1domain::requestinterface::ReadFooRequest::default_instance());
}

ReadRequest::ReadRequest(const ReadRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample1domain.requestinterface.ReadRequest)
}

void ReadRequest::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  readfoorequest_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReadRequest::~ReadRequest() {
  // @@protoc_insertion_point(destructor:cmexample1domain.requestinterface.ReadRequest)
  SharedDtor();
}

void ReadRequest::SharedDtor() {
  if (this != default_instance_) {
    delete readfoorequest_;
  }
}

void ReadRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadRequest_descriptor_;
}

const ReadRequest& ReadRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample1domain_2frequestinterface_2freadrequest_2eproto();
  return *default_instance_;
}

ReadRequest* ReadRequest::default_instance_ = NULL;

ReadRequest* ReadRequest::New() const {
  return new ReadRequest;
}

void ReadRequest::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    type_ = 0;
    if (has_readfoorequest()) {
      if (readfoorequest_ != NULL) readfoorequest_->::cmexample1domain::requestinterface::ReadFooRequest::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample1domain.requestinterface.ReadRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .cmexample1domain.requestinterface.ReadRequest.Type type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::cmexample1domain::requestinterface::ReadRequest_Type_IsValid(value)) {
            set_type(static_cast< ::cmexample1domain::requestinterface::ReadRequest_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_readFooRequest;
        break;
      }

      // optional .cmexample1domain.requestinterface.ReadFooRequest readFooRequest = 2;
      case 2: {
        if (tag == 18) {
         parse_readFooRequest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_readfoorequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample1domain.requestinterface.ReadRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample1domain.requestinterface.ReadRequest)
  return false;
#undef DO_
}

void ReadRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample1domain.requestinterface.ReadRequest)
  // optional .cmexample1domain.requestinterface.ReadRequest.Type type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .cmexample1domain.requestinterface.ReadFooRequest readFooRequest = 2;
  if (has_readfoorequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->readfoorequest(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample1domain.requestinterface.ReadRequest)
}

::google::protobuf::uint8* ReadRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample1domain.requestinterface.ReadRequest)
  // optional .cmexample1domain.requestinterface.ReadRequest.Type type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .cmexample1domain.requestinterface.ReadFooRequest readFooRequest = 2;
  if (has_readfoorequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->readfoorequest(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample1domain.requestinterface.ReadRequest)
  return target;
}

int ReadRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .cmexample1domain.requestinterface.ReadRequest.Type type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional .cmexample1domain.requestinterface.ReadFooRequest readFooRequest = 2;
    if (has_readfoorequest()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->readfoorequest());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadRequest::MergeFrom(const ReadRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_readfoorequest()) {
      mutable_readfoorequest()->::cmexample1domain::requestinterface::ReadFooRequest::MergeFrom(from.readfoorequest());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadRequest::CopyFrom(const ReadRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadRequest::IsInitialized() const {

  return true;
}

void ReadRequest::Swap(ReadRequest* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(readfoorequest_, other->readfoorequest_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadRequest_descriptor_;
  metadata.reflection = ReadRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample1domain

// @@protoc_insertion_point(global_scope)
