// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/databasevalues/foodescription.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample1domain/databasevalues/foodescription.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace databasevalues {

namespace {

const ::google::protobuf::Descriptor* FooDescription_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FooDescription_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample1domain/databasevalues/foodescription.proto");
  GOOGLE_CHECK(file != NULL);
  FooDescription_descriptor_ = file->message_type(0);
  static const int FooDescription_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FooDescription, description_),
  };
  FooDescription_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FooDescription_descriptor_,
      FooDescription::default_instance_,
      FooDescription_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FooDescription, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FooDescription, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FooDescription));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FooDescription_descriptor_, &FooDescription::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto() {
  delete FooDescription::default_instance_;
  delete FooDescription_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n=protobuf/cmexample1domain/databasevalu"
    "es/foodescription.proto\022\037cmexample1domai"
    "n.databasevalues\"%\n\016FooDescription\022\023\n\013de"
    "scription\030\001 \001(\t", 135);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample1domain/databasevalues/foodescription.proto", &protobuf_RegisterTypes);
  FooDescription::default_instance_ = new FooDescription();
  FooDescription::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FooDescription::kDescriptionFieldNumber;
#endif  // !_MSC_VER

FooDescription::FooDescription()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample1domain.databasevalues.FooDescription)
}

void FooDescription::InitAsDefaultInstance() {
}

FooDescription::FooDescription(const FooDescription& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample1domain.databasevalues.FooDescription)
}

void FooDescription::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FooDescription::~FooDescription() {
  // @@protoc_insertion_point(destructor:cmexample1domain.databasevalues.FooDescription)
  SharedDtor();
}

void FooDescription::SharedDtor() {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (this != default_instance_) {
  }
}

void FooDescription::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FooDescription::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FooDescription_descriptor_;
}

const FooDescription& FooDescription::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
  return *default_instance_;
}

FooDescription* FooDescription::default_instance_ = NULL;

FooDescription* FooDescription::New() const {
  return new FooDescription;
}

void FooDescription::Clear() {
  if (has_description()) {
    if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      description_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FooDescription::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample1domain.databasevalues.FooDescription)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string description = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample1domain.databasevalues.FooDescription)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample1domain.databasevalues.FooDescription)
  return false;
#undef DO_
}

void FooDescription::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample1domain.databasevalues.FooDescription)
  // optional string description = 1;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->description(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample1domain.databasevalues.FooDescription)
}

::google::protobuf::uint8* FooDescription::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample1domain.databasevalues.FooDescription)
  // optional string description = 1;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->description(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample1domain.databasevalues.FooDescription)
  return target;
}

int FooDescription::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string description = 1;
    if (has_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->description());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FooDescription::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FooDescription* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FooDescription*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FooDescription::MergeFrom(const FooDescription& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_description()) {
      set_description(from.description());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FooDescription::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FooDescription::CopyFrom(const FooDescription& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FooDescription::IsInitialized() const {

  return true;
}

void FooDescription::Swap(FooDescription* other) {
  if (other != this) {
    std::swap(description_, other->description_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FooDescription::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FooDescription_descriptor_;
  metadata.reflection = FooDescription_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample1domain

// @@protoc_insertion_point(global_scope)
