// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/databasevalues/foodescription.proto

#ifndef PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace databasevalues {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();

class FooDescription;

// ===================================================================

class FooDescription : public ::google::protobuf::Message {
 public:
  FooDescription();
  virtual ~FooDescription();

  FooDescription(const FooDescription& from);

  inline FooDescription& operator=(const FooDescription& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FooDescription& default_instance();

  void Swap(FooDescription* other);

  // implements Message ----------------------------------------------

  FooDescription* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FooDescription& from);
  void MergeFrom(const FooDescription& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string description = 1;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 1;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // @@protoc_insertion_point(class_scope:cmexample1domain.databasevalues.FooDescription)
 private:
  inline void set_has_description();
  inline void clear_has_description();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* description_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto();

  void InitAsDefaultInstance();
  static FooDescription* default_instance_;
};
// ===================================================================


// ===================================================================

// FooDescription

// optional string description = 1;
inline bool FooDescription::has_description() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FooDescription::set_has_description() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FooDescription::clear_has_description() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FooDescription::clear_description() {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& FooDescription::description() const {
  // @@protoc_insertion_point(field_get:cmexample1domain.databasevalues.FooDescription.description)
  return *description_;
}
inline void FooDescription::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set:cmexample1domain.databasevalues.FooDescription.description)
}
inline void FooDescription::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample1domain.databasevalues.FooDescription.description)
}
inline void FooDescription::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample1domain.databasevalues.FooDescription.description)
}
inline ::std::string* FooDescription::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:cmexample1domain.databasevalues.FooDescription.description)
  return description_;
}
inline ::std::string* FooDescription::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void FooDescription::set_allocated_description(::std::string* description) {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample1domain.databasevalues.FooDescription.description)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample1domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoodescription_2eproto__INCLUDED
