// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample1domain/databasevalues/foovalues.proto

#ifndef PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample1domain {
namespace databasevalues {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();

class FooValues;

// ===================================================================

class FooValues : public ::google::protobuf::Message {
 public:
  FooValues();
  virtual ~FooValues();

  FooValues(const FooValues& from);

  inline FooValues& operator=(const FooValues& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FooValues& default_instance();

  void Swap(FooValues* other);

  // implements Message ----------------------------------------------

  FooValues* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FooValues& from);
  void MergeFrom(const FooValues& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string value = 1;
  inline int value_size() const;
  inline void clear_value();
  static const int kValueFieldNumber = 1;
  inline const ::std::string& value(int index) const;
  inline ::std::string* mutable_value(int index);
  inline void set_value(int index, const ::std::string& value);
  inline void set_value(int index, const char* value);
  inline void set_value(int index, const char* value, size_t size);
  inline ::std::string* add_value();
  inline void add_value(const ::std::string& value);
  inline void add_value(const char* value);
  inline void add_value(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& value() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_value();

  // @@protoc_insertion_point(class_scope:cmexample1domain.databasevalues.FooValues)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> value_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto();

  void InitAsDefaultInstance();
  static FooValues* default_instance_;
};
// ===================================================================


// ===================================================================

// FooValues

// repeated string value = 1;
inline int FooValues::value_size() const {
  return value_.size();
}
inline void FooValues::clear_value() {
  value_.Clear();
}
inline const ::std::string& FooValues::value(int index) const {
  // @@protoc_insertion_point(field_get:cmexample1domain.databasevalues.FooValues.value)
  return value_.Get(index);
}
inline ::std::string* FooValues::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:cmexample1domain.databasevalues.FooValues.value)
  return value_.Mutable(index);
}
inline void FooValues::set_value(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:cmexample1domain.databasevalues.FooValues.value)
  value_.Mutable(index)->assign(value);
}
inline void FooValues::set_value(int index, const char* value) {
  value_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample1domain.databasevalues.FooValues.value)
}
inline void FooValues::set_value(int index, const char* value, size_t size) {
  value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample1domain.databasevalues.FooValues.value)
}
inline ::std::string* FooValues::add_value() {
  return value_.Add();
}
inline void FooValues::add_value(const ::std::string& value) {
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:cmexample1domain.databasevalues.FooValues.value)
}
inline void FooValues::add_value(const char* value) {
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:cmexample1domain.databasevalues.FooValues.value)
}
inline void FooValues::add_value(const char* value, size_t size) {
  value_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:cmexample1domain.databasevalues.FooValues.value)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FooValues::value() const {
  // @@protoc_insertion_point(field_list:cmexample1domain.databasevalues.FooValues.value)
  return value_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FooValues::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:cmexample1domain.databasevalues.FooValues.value)
  return &value_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace databasevalues
}  // namespace cmexample1domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample1domain_2fdatabasevalues_2ffoovalues_2eproto__INCLUDED
