// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/addcitizenrequest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/addcitizenrequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* AddCitizenRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AddCitizenRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/addcitizenrequest.proto");
  GOOGLE_CHECK(file != NULL);
  AddCitizenRequest_descriptor_ = file->message_type(0);
  static const int AddCitizenRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddCitizenRequest, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddCitizenRequest, tax_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddCitizenRequest, building_),
  };
  AddCitizenRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AddCitizenRequest_descriptor_,
      AddCitizenRequest::default_instance_,
      AddCitizenRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddCitizenRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AddCitizenRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AddCitizenRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AddCitizenRequest_descriptor_, &AddCitizenRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto() {
  delete AddCitizenRequest::default_instance_;
  delete AddCitizenRequest_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nBprotobuf/cmexample2domain/requestinter"
    "face/addcitizenrequest.proto\022!cmexample2"
    "domain.requestinterface\"@\n\021AddCitizenReq"
    "uest\022\014\n\004name\030\001 \001(\t\022\013\n\003tax\030\002 \001(\r\022\020\n\010build"
    "ing\030\003 \001(\t", 169);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/addcitizenrequest.proto", &protobuf_RegisterTypes);
  AddCitizenRequest::default_instance_ = new AddCitizenRequest();
  AddCitizenRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AddCitizenRequest::kNameFieldNumber;
const int AddCitizenRequest::kTaxFieldNumber;
const int AddCitizenRequest::kBuildingFieldNumber;
#endif  // !_MSC_VER

AddCitizenRequest::AddCitizenRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.AddCitizenRequest)
}

void AddCitizenRequest::InitAsDefaultInstance() {
}

AddCitizenRequest::AddCitizenRequest(const AddCitizenRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.AddCitizenRequest)
}

void AddCitizenRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tax_ = 0u;
  building_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AddCitizenRequest::~AddCitizenRequest() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.AddCitizenRequest)
  SharedDtor();
}

void AddCitizenRequest::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete building_;
  }
  if (this != default_instance_) {
  }
}

void AddCitizenRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AddCitizenRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AddCitizenRequest_descriptor_;
}

const AddCitizenRequest& AddCitizenRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto();
  return *default_instance_;
}

AddCitizenRequest* AddCitizenRequest::default_instance_ = NULL;

AddCitizenRequest* AddCitizenRequest::New() const {
  return new AddCitizenRequest;
}

void AddCitizenRequest::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    tax_ = 0u;
    if (has_building()) {
      if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        building_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AddCitizenRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.AddCitizenRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_tax;
        break;
      }

      // optional uint32 tax = 2;
      case 2: {
        if (tag == 16) {
         parse_tax:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &tax_)));
          set_has_tax();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_building;
        break;
      }

      // optional string building = 3;
      case 3: {
        if (tag == 26) {
         parse_building:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_building()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->building().data(), this->building().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "building");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.AddCitizenRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.AddCitizenRequest)
  return false;
#undef DO_
}

void AddCitizenRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.AddCitizenRequest)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional uint32 tax = 2;
  if (has_tax()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->tax(), output);
  }

  // optional string building = 3;
  if (has_building()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->building().data(), this->building().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "building");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->building(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.AddCitizenRequest)
}

::google::protobuf::uint8* AddCitizenRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.AddCitizenRequest)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional uint32 tax = 2;
  if (has_tax()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->tax(), target);
  }

  // optional string building = 3;
  if (has_building()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->building().data(), this->building().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "building");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->building(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.AddCitizenRequest)
  return target;
}

int AddCitizenRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional uint32 tax = 2;
    if (has_tax()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->tax());
    }

    // optional string building = 3;
    if (has_building()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->building());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AddCitizenRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AddCitizenRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AddCitizenRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AddCitizenRequest::MergeFrom(const AddCitizenRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_tax()) {
      set_tax(from.tax());
    }
    if (from.has_building()) {
      set_building(from.building());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AddCitizenRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddCitizenRequest::CopyFrom(const AddCitizenRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddCitizenRequest::IsInitialized() const {

  return true;
}

void AddCitizenRequest::Swap(AddCitizenRequest* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(tax_, other->tax_);
    std::swap(building_, other->building_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AddCitizenRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AddCitizenRequest_descriptor_;
  metadata.reflection = AddCitizenRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
