// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/clearallrequest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/clearallrequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ClearAllRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClearAllRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/clearallrequest.proto");
  GOOGLE_CHECK(file != NULL);
  ClearAllRequest_descriptor_ = file->message_type(0);
  static const int ClearAllRequest_offsets_[1] = {
  };
  ClearAllRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClearAllRequest_descriptor_,
      ClearAllRequest::default_instance_,
      ClearAllRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClearAllRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClearAllRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClearAllRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClearAllRequest_descriptor_, &ClearAllRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto() {
  delete ClearAllRequest::default_instance_;
  delete ClearAllRequest_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n@protobuf/cmexample2domain/requestinter"
    "face/clearallrequest.proto\022!cmexample2do"
    "main.requestinterface\"\021\n\017ClearAllRequest", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/clearallrequest.proto", &protobuf_RegisterTypes);
  ClearAllRequest::default_instance_ = new ClearAllRequest();
  ClearAllRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

ClearAllRequest::ClearAllRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.ClearAllRequest)
}

void ClearAllRequest::InitAsDefaultInstance() {
}

ClearAllRequest::ClearAllRequest(const ClearAllRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.ClearAllRequest)
}

void ClearAllRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClearAllRequest::~ClearAllRequest() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.ClearAllRequest)
  SharedDtor();
}

void ClearAllRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClearAllRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClearAllRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClearAllRequest_descriptor_;
}

const ClearAllRequest& ClearAllRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto();
  return *default_instance_;
}

ClearAllRequest* ClearAllRequest::default_instance_ = NULL;

ClearAllRequest* ClearAllRequest::New() const {
  return new ClearAllRequest;
}

void ClearAllRequest::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClearAllRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.ClearAllRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.ClearAllRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.ClearAllRequest)
  return false;
#undef DO_
}

void ClearAllRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.ClearAllRequest)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.ClearAllRequest)
}

::google::protobuf::uint8* ClearAllRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.ClearAllRequest)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.ClearAllRequest)
  return target;
}

int ClearAllRequest::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClearAllRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClearAllRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClearAllRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClearAllRequest::MergeFrom(const ClearAllRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClearAllRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClearAllRequest::CopyFrom(const ClearAllRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClearAllRequest::IsInitialized() const {

  return true;
}

void ClearAllRequest::Swap(ClearAllRequest* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClearAllRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClearAllRequest_descriptor_;
  metadata.reflection = ClearAllRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
