// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readcitizensresponse.proto

#ifndef PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();

class ReadCitizensResponse;
class CitizenInfo;

// ===================================================================

class ReadCitizensResponse : public ::google::protobuf::Message {
 public:
  ReadCitizensResponse();
  virtual ~ReadCitizensResponse();

  ReadCitizensResponse(const ReadCitizensResponse& from);

  inline ReadCitizensResponse& operator=(const ReadCitizensResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadCitizensResponse& default_instance();

  void Swap(ReadCitizensResponse* other);

  // implements Message ----------------------------------------------

  ReadCitizensResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadCitizensResponse& from);
  void MergeFrom(const ReadCitizensResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cmexample2domain.requestinterface.CitizenInfo citizenInfo = 1;
  inline int citizeninfo_size() const;
  inline void clear_citizeninfo();
  static const int kCitizenInfoFieldNumber = 1;
  inline const ::cmexample2domain::requestinterface::CitizenInfo& citizeninfo(int index) const;
  inline ::cmexample2domain::requestinterface::CitizenInfo* mutable_citizeninfo(int index);
  inline ::cmexample2domain::requestinterface::CitizenInfo* add_citizeninfo();
  inline const ::google::protobuf::RepeatedPtrField< ::cmexample2domain::requestinterface::CitizenInfo >&
      citizeninfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::cmexample2domain::requestinterface::CitizenInfo >*
      mutable_citizeninfo();

  // @@protoc_insertion_point(class_scope:cmexample2domain.requestinterface.ReadCitizensResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cmexample2domain::requestinterface::CitizenInfo > citizeninfo_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();

  void InitAsDefaultInstance();
  static ReadCitizensResponse* default_instance_;
};
// -------------------------------------------------------------------

class CitizenInfo : public ::google::protobuf::Message {
 public:
  CitizenInfo();
  virtual ~CitizenInfo();

  CitizenInfo(const CitizenInfo& from);

  inline CitizenInfo& operator=(const CitizenInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CitizenInfo& default_instance();

  void Swap(CitizenInfo* other);

  // implements Message ----------------------------------------------

  CitizenInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CitizenInfo& from);
  void MergeFrom(const CitizenInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 tax = 2;
  inline bool has_tax() const;
  inline void clear_tax();
  static const int kTaxFieldNumber = 2;
  inline ::google::protobuf::int32 tax() const;
  inline void set_tax(::google::protobuf::int32 value);

  // optional string building = 3;
  inline bool has_building() const;
  inline void clear_building();
  static const int kBuildingFieldNumber = 3;
  inline const ::std::string& building() const;
  inline void set_building(const ::std::string& value);
  inline void set_building(const char* value);
  inline void set_building(const char* value, size_t size);
  inline ::std::string* mutable_building();
  inline ::std::string* release_building();
  inline void set_allocated_building(::std::string* building);

  // @@protoc_insertion_point(class_scope:cmexample2domain.requestinterface.CitizenInfo)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_tax();
  inline void clear_has_tax();
  inline void set_has_building();
  inline void clear_has_building();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* building_;
  ::google::protobuf::int32 tax_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();

  void InitAsDefaultInstance();
  static CitizenInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// ReadCitizensResponse

// repeated .cmexample2domain.requestinterface.CitizenInfo citizenInfo = 1;
inline int ReadCitizensResponse::citizeninfo_size() const {
  return citizeninfo_.size();
}
inline void ReadCitizensResponse::clear_citizeninfo() {
  citizeninfo_.Clear();
}
inline const ::cmexample2domain::requestinterface::CitizenInfo& ReadCitizensResponse::citizeninfo(int index) const {
  // @@protoc_insertion_point(field_get:cmexample2domain.requestinterface.ReadCitizensResponse.citizenInfo)
  return citizeninfo_.Get(index);
}
inline ::cmexample2domain::requestinterface::CitizenInfo* ReadCitizensResponse::mutable_citizeninfo(int index) {
  // @@protoc_insertion_point(field_mutable:cmexample2domain.requestinterface.ReadCitizensResponse.citizenInfo)
  return citizeninfo_.Mutable(index);
}
inline ::cmexample2domain::requestinterface::CitizenInfo* ReadCitizensResponse::add_citizeninfo() {
  // @@protoc_insertion_point(field_add:cmexample2domain.requestinterface.ReadCitizensResponse.citizenInfo)
  return citizeninfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cmexample2domain::requestinterface::CitizenInfo >&
ReadCitizensResponse::citizeninfo() const {
  // @@protoc_insertion_point(field_list:cmexample2domain.requestinterface.ReadCitizensResponse.citizenInfo)
  return citizeninfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::cmexample2domain::requestinterface::CitizenInfo >*
ReadCitizensResponse::mutable_citizeninfo() {
  // @@protoc_insertion_point(field_mutable_list:cmexample2domain.requestinterface.ReadCitizensResponse.citizenInfo)
  return &citizeninfo_;
}

// -------------------------------------------------------------------

// CitizenInfo

// optional string name = 1;
inline bool CitizenInfo::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CitizenInfo::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CitizenInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CitizenInfo::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& CitizenInfo::name() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.requestinterface.CitizenInfo.name)
  return *name_;
}
inline void CitizenInfo::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:cmexample2domain.requestinterface.CitizenInfo.name)
}
inline void CitizenInfo::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample2domain.requestinterface.CitizenInfo.name)
}
inline void CitizenInfo::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample2domain.requestinterface.CitizenInfo.name)
}
inline ::std::string* CitizenInfo::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:cmexample2domain.requestinterface.CitizenInfo.name)
  return name_;
}
inline ::std::string* CitizenInfo::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CitizenInfo::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample2domain.requestinterface.CitizenInfo.name)
}

// optional int32 tax = 2;
inline bool CitizenInfo::has_tax() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CitizenInfo::set_has_tax() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CitizenInfo::clear_has_tax() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CitizenInfo::clear_tax() {
  tax_ = 0;
  clear_has_tax();
}
inline ::google::protobuf::int32 CitizenInfo::tax() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.requestinterface.CitizenInfo.tax)
  return tax_;
}
inline void CitizenInfo::set_tax(::google::protobuf::int32 value) {
  set_has_tax();
  tax_ = value;
  // @@protoc_insertion_point(field_set:cmexample2domain.requestinterface.CitizenInfo.tax)
}

// optional string building = 3;
inline bool CitizenInfo::has_building() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CitizenInfo::set_has_building() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CitizenInfo::clear_has_building() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CitizenInfo::clear_building() {
  if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_->clear();
  }
  clear_has_building();
}
inline const ::std::string& CitizenInfo::building() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.requestinterface.CitizenInfo.building)
  return *building_;
}
inline void CitizenInfo::set_building(const ::std::string& value) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(value);
  // @@protoc_insertion_point(field_set:cmexample2domain.requestinterface.CitizenInfo.building)
}
inline void CitizenInfo::set_building(const char* value) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(value);
  // @@protoc_insertion_point(field_set_char:cmexample2domain.requestinterface.CitizenInfo.building)
}
inline void CitizenInfo::set_building(const char* value, size_t size) {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  building_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:cmexample2domain.requestinterface.CitizenInfo.building)
}
inline ::std::string* CitizenInfo::mutable_building() {
  set_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    building_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:cmexample2domain.requestinterface.CitizenInfo.building)
  return building_;
}
inline ::std::string* CitizenInfo::release_building() {
  clear_has_building();
  if (building_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = building_;
    building_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void CitizenInfo::set_allocated_building(::std::string* building) {
  if (building_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete building_;
  }
  if (building) {
    set_has_building();
    building_ = building;
  } else {
    clear_has_building();
    building_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:cmexample2domain.requestinterface.CitizenInfo.building)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto__INCLUDED
