// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readrequest.proto

#ifndef PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();
void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();
void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();

class ReadRequest;

enum ReadRequest_Type {
  ReadRequest_Type_UNKNOWN = 0,
  ReadRequest_Type_READ_TOWN_SUMMARY = 1,
  ReadRequest_Type_READ_INFRASTRUCTURE = 2,
  ReadRequest_Type_READ_CITIZENS = 3
};
bool ReadRequest_Type_IsValid(int value);
const ReadRequest_Type ReadRequest_Type_Type_MIN = ReadRequest_Type_UNKNOWN;
const ReadRequest_Type ReadRequest_Type_Type_MAX = ReadRequest_Type_READ_CITIZENS;
const int ReadRequest_Type_Type_ARRAYSIZE = ReadRequest_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReadRequest_Type_descriptor();
inline const ::std::string& ReadRequest_Type_Name(ReadRequest_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReadRequest_Type_descriptor(), value);
}
inline bool ReadRequest_Type_Parse(
    const ::std::string& name, ReadRequest_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReadRequest_Type>(
    ReadRequest_Type_descriptor(), name, value);
}
// ===================================================================

class ReadRequest : public ::google::protobuf::Message {
 public:
  ReadRequest();
  virtual ~ReadRequest();

  ReadRequest(const ReadRequest& from);

  inline ReadRequest& operator=(const ReadRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadRequest& default_instance();

  void Swap(ReadRequest* other);

  // implements Message ----------------------------------------------

  ReadRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadRequest& from);
  void MergeFrom(const ReadRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ReadRequest_Type Type;
  static const Type UNKNOWN = ReadRequest_Type_UNKNOWN;
  static const Type READ_TOWN_SUMMARY = ReadRequest_Type_READ_TOWN_SUMMARY;
  static const Type READ_INFRASTRUCTURE = ReadRequest_Type_READ_INFRASTRUCTURE;
  static const Type READ_CITIZENS = ReadRequest_Type_READ_CITIZENS;
  static inline bool Type_IsValid(int value) {
    return ReadRequest_Type_IsValid(value);
  }
  static const Type Type_MIN =
    ReadRequest_Type_Type_MIN;
  static const Type Type_MAX =
    ReadRequest_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    ReadRequest_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return ReadRequest_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return ReadRequest_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return ReadRequest_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .cmexample2domain.requestinterface.ReadRequest.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::cmexample2domain::requestinterface::ReadRequest_Type type() const;
  inline void set_type(::cmexample2domain::requestinterface::ReadRequest_Type value);

  // @@protoc_insertion_point(class_scope:cmexample2domain.requestinterface.ReadRequest)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  friend void  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto();

  void InitAsDefaultInstance();
  static ReadRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// ReadRequest

// optional .cmexample2domain.requestinterface.ReadRequest.Type type = 1;
inline bool ReadRequest::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReadRequest::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReadRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReadRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::cmexample2domain::requestinterface::ReadRequest_Type ReadRequest::type() const {
  // @@protoc_insertion_point(field_get:cmexample2domain.requestinterface.ReadRequest.type)
  return static_cast< ::cmexample2domain::requestinterface::ReadRequest_Type >(type_);
}
inline void ReadRequest::set_type(::cmexample2domain::requestinterface::ReadRequest_Type value) {
  assert(::cmexample2domain::requestinterface::ReadRequest_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:cmexample2domain.requestinterface.ReadRequest.type)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cmexample2domain::requestinterface::ReadRequest_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cmexample2domain::requestinterface::ReadRequest_Type>() {
  return ::cmexample2domain::requestinterface::ReadRequest_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fcmexample2domain_2frequestinterface_2freadrequest_2eproto__INCLUDED
