// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readwriterequest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/readwriterequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadWriteRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadWriteRequest_reflection_ = NULL;
struct ReadWriteRequestOneofInstance {
  const ::cmexample2domain::requestinterface::AddBuildingRequest* addbuildingrequest_;
  const ::cmexample2domain::requestinterface::DeleteBuildingRequest* deletebuildingrequest_;
  const ::cmexample2domain::requestinterface::AddCitizenRequest* addcitizenrequest_;
  const ::cmexample2domain::requestinterface::DeleteCitizenRequest* deletecitizenrequest_;
  const ::cmexample2domain::requestinterface::ClearAllRequest* clearallrequest_;
}* ReadWriteRequest_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/readwriterequest.proto");
  GOOGLE_CHECK(file != NULL);
  ReadWriteRequest_descriptor_ = file->message_type(0);
  static const int ReadWriteRequest_offsets_[6] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadWriteRequest_default_oneof_instance_, addbuildingrequest_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadWriteRequest_default_oneof_instance_, deletebuildingrequest_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadWriteRequest_default_oneof_instance_, addcitizenrequest_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadWriteRequest_default_oneof_instance_, deletecitizenrequest_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadWriteRequest_default_oneof_instance_, clearallrequest_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadWriteRequest, readWriteRequest_),
  };
  ReadWriteRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadWriteRequest_descriptor_,
      ReadWriteRequest::default_instance_,
      ReadWriteRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadWriteRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadWriteRequest, _unknown_fields_),
      -1,
      ReadWriteRequest_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadWriteRequest, _oneof_case_[0]),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadWriteRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadWriteRequest_descriptor_, &ReadWriteRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto() {
  delete ReadWriteRequest::default_instance_;
  delete ReadWriteRequest_default_oneof_instance_;
  delete ReadWriteRequest_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddbuildingrequest_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fdeletebuildingrequest_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2faddcitizenrequest_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fdeletecitizenrequest_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2fclearallrequest_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nAprotobuf/cmexample2domain/requestinter"
    "face/readwriterequest.proto\022!cmexample2d"
    "omain.requestinterface\032Cprotobuf/cmexamp"
    "le2domain/requestinterface/addbuildingre"
    "quest.proto\032Fprotobuf/cmexample2domain/r"
    "equestinterface/deletebuildingrequest.pr"
    "oto\032Bprotobuf/cmexample2domain/requestin"
    "terface/addcitizenrequest.proto\032Eprotobu"
    "f/cmexample2domain/requestinterface/dele"
    "tecitizenrequest.proto\032@protobuf/cmexamp"
    "le2domain/requestinterface/clearallreque"
    "st.proto\"\321\003\n\020ReadWriteRequest\022S\n\022addBuil"
    "dingRequest\030\001 \001(\01325.cmexample2domain.req"
    "uestinterface.AddBuildingRequestH\000\022Y\n\025de"
    "leteBuildingRequest\030\002 \001(\01328.cmexample2do"
    "main.requestinterface.DeleteBuildingRequ"
    "estH\000\022Q\n\021addCitizenRequest\030\003 \001(\01324.cmexa"
    "mple2domain.requestinterface.AddCitizenR"
    "equestH\000\022W\n\024deleteCitizenRequest\030\004 \001(\01327"
    ".cmexample2domain.requestinterface.Delet"
    "eCitizenRequestH\000\022M\n\017clearAllRequest\030\005 \001"
    "(\01322.cmexample2domain.requestinterface.C"
    "learAllRequestH\000B\022\n\020readWriteRequest", 916);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/readwriterequest.proto", &protobuf_RegisterTypes);
  ReadWriteRequest::default_instance_ = new ReadWriteRequest();
  ReadWriteRequest_default_oneof_instance_ = new ReadWriteRequestOneofInstance;
  ReadWriteRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ReadWriteRequest::kAddBuildingRequestFieldNumber;
const int ReadWriteRequest::kDeleteBuildingRequestFieldNumber;
const int ReadWriteRequest::kAddCitizenRequestFieldNumber;
const int ReadWriteRequest::kDeleteCitizenRequestFieldNumber;
const int ReadWriteRequest::kClearAllRequestFieldNumber;
#endif  // !_MSC_VER

ReadWriteRequest::ReadWriteRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.ReadWriteRequest)
}

void ReadWriteRequest::InitAsDefaultInstance() {
  ReadWriteRequest_default_oneof_instance_->addbuildingrequest_ = const_cast< ::cmexample2domain::requestinterface::AddBuildingRequest*>(&::cmexample2domain::requestinterface::AddBuildingRequest::default_instance());
  ReadWriteRequest_default_oneof_instance_->deletebuildingrequest_ = const_cast< ::cmexample2domain::requestinterface::DeleteBuildingRequest*>(&::cmexample2domain::requestinterface::DeleteBuildingRequest::default_instance());
  ReadWriteRequest_default_oneof_instance_->addcitizenrequest_ = const_cast< ::cmexample2domain::requestinterface::AddCitizenRequest*>(&::cmexample2domain::requestinterface::AddCitizenRequest::default_instance());
  ReadWriteRequest_default_oneof_instance_->deletecitizenrequest_ = const_cast< ::cmexample2domain::requestinterface::DeleteCitizenRequest*>(&::cmexample2domain::requestinterface::DeleteCitizenRequest::default_instance());
  ReadWriteRequest_default_oneof_instance_->clearallrequest_ = const_cast< ::cmexample2domain::requestinterface::ClearAllRequest*>(&::cmexample2domain::requestinterface::ClearAllRequest::default_instance());
}

ReadWriteRequest::ReadWriteRequest(const ReadWriteRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.ReadWriteRequest)
}

void ReadWriteRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_readWriteRequest();
}

ReadWriteRequest::~ReadWriteRequest() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.ReadWriteRequest)
  SharedDtor();
}

void ReadWriteRequest::SharedDtor() {
  if (has_readWriteRequest()) {
    clear_readWriteRequest();
  }
  if (this != default_instance_) {
  }
}

void ReadWriteRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadWriteRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadWriteRequest_descriptor_;
}

const ReadWriteRequest& ReadWriteRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadwriterequest_2eproto();
  return *default_instance_;
}

ReadWriteRequest* ReadWriteRequest::default_instance_ = NULL;

ReadWriteRequest* ReadWriteRequest::New() const {
  return new ReadWriteRequest;
}

void ReadWriteRequest::clear_readWriteRequest() {
  switch(readWriteRequest_case()) {
    case kAddBuildingRequest: {
      delete readWriteRequest_.addbuildingrequest_;
      break;
    }
    case kDeleteBuildingRequest: {
      delete readWriteRequest_.deletebuildingrequest_;
      break;
    }
    case kAddCitizenRequest: {
      delete readWriteRequest_.addcitizenrequest_;
      break;
    }
    case kDeleteCitizenRequest: {
      delete readWriteRequest_.deletecitizenrequest_;
      break;
    }
    case kClearAllRequest: {
      delete readWriteRequest_.clearallrequest_;
      break;
    }
    case READWRITEREQUEST_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = READWRITEREQUEST_NOT_SET;
}


void ReadWriteRequest::Clear() {
  clear_readWriteRequest();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadWriteRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.ReadWriteRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .cmexample2domain.requestinterface.AddBuildingRequest addBuildingRequest = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addbuildingrequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_deleteBuildingRequest;
        break;
      }

      // optional .cmexample2domain.requestinterface.DeleteBuildingRequest deleteBuildingRequest = 2;
      case 2: {
        if (tag == 18) {
         parse_deleteBuildingRequest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_deletebuildingrequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_addCitizenRequest;
        break;
      }

      // optional .cmexample2domain.requestinterface.AddCitizenRequest addCitizenRequest = 3;
      case 3: {
        if (tag == 26) {
         parse_addCitizenRequest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addcitizenrequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_deleteCitizenRequest;
        break;
      }

      // optional .cmexample2domain.requestinterface.DeleteCitizenRequest deleteCitizenRequest = 4;
      case 4: {
        if (tag == 34) {
         parse_deleteCitizenRequest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_deletecitizenrequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_clearAllRequest;
        break;
      }

      // optional .cmexample2domain.requestinterface.ClearAllRequest clearAllRequest = 5;
      case 5: {
        if (tag == 42) {
         parse_clearAllRequest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_clearallrequest()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.ReadWriteRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.ReadWriteRequest)
  return false;
#undef DO_
}

void ReadWriteRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.ReadWriteRequest)
  // optional .cmexample2domain.requestinterface.AddBuildingRequest addBuildingRequest = 1;
  if (has_addbuildingrequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->addbuildingrequest(), output);
  }

  // optional .cmexample2domain.requestinterface.DeleteBuildingRequest deleteBuildingRequest = 2;
  if (has_deletebuildingrequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->deletebuildingrequest(), output);
  }

  // optional .cmexample2domain.requestinterface.AddCitizenRequest addCitizenRequest = 3;
  if (has_addcitizenrequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->addcitizenrequest(), output);
  }

  // optional .cmexample2domain.requestinterface.DeleteCitizenRequest deleteCitizenRequest = 4;
  if (has_deletecitizenrequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->deletecitizenrequest(), output);
  }

  // optional .cmexample2domain.requestinterface.ClearAllRequest clearAllRequest = 5;
  if (has_clearallrequest()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->clearallrequest(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.ReadWriteRequest)
}

::google::protobuf::uint8* ReadWriteRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.ReadWriteRequest)
  // optional .cmexample2domain.requestinterface.AddBuildingRequest addBuildingRequest = 1;
  if (has_addbuildingrequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->addbuildingrequest(), target);
  }

  // optional .cmexample2domain.requestinterface.DeleteBuildingRequest deleteBuildingRequest = 2;
  if (has_deletebuildingrequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->deletebuildingrequest(), target);
  }

  // optional .cmexample2domain.requestinterface.AddCitizenRequest addCitizenRequest = 3;
  if (has_addcitizenrequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->addcitizenrequest(), target);
  }

  // optional .cmexample2domain.requestinterface.DeleteCitizenRequest deleteCitizenRequest = 4;
  if (has_deletecitizenrequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->deletecitizenrequest(), target);
  }

  // optional .cmexample2domain.requestinterface.ClearAllRequest clearAllRequest = 5;
  if (has_clearallrequest()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->clearallrequest(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.ReadWriteRequest)
  return target;
}

int ReadWriteRequest::ByteSize() const {
  int total_size = 0;

  switch (readWriteRequest_case()) {
    // optional .cmexample2domain.requestinterface.AddBuildingRequest addBuildingRequest = 1;
    case kAddBuildingRequest: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->addbuildingrequest());
      break;
    }
    // optional .cmexample2domain.requestinterface.DeleteBuildingRequest deleteBuildingRequest = 2;
    case kDeleteBuildingRequest: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->deletebuildingrequest());
      break;
    }
    // optional .cmexample2domain.requestinterface.AddCitizenRequest addCitizenRequest = 3;
    case kAddCitizenRequest: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->addcitizenrequest());
      break;
    }
    // optional .cmexample2domain.requestinterface.DeleteCitizenRequest deleteCitizenRequest = 4;
    case kDeleteCitizenRequest: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->deletecitizenrequest());
      break;
    }
    // optional .cmexample2domain.requestinterface.ClearAllRequest clearAllRequest = 5;
    case kClearAllRequest: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->clearallrequest());
      break;
    }
    case READWRITEREQUEST_NOT_SET: {
      break;
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadWriteRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadWriteRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadWriteRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadWriteRequest::MergeFrom(const ReadWriteRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  switch (from.readWriteRequest_case()) {
    case kAddBuildingRequest: {
      mutable_addbuildingrequest()->::cmexample2domain::requestinterface::AddBuildingRequest::MergeFrom(from.addbuildingrequest());
      break;
    }
    case kDeleteBuildingRequest: {
      mutable_deletebuildingrequest()->::cmexample2domain::requestinterface::DeleteBuildingRequest::MergeFrom(from.deletebuildingrequest());
      break;
    }
    case kAddCitizenRequest: {
      mutable_addcitizenrequest()->::cmexample2domain::requestinterface::AddCitizenRequest::MergeFrom(from.addcitizenrequest());
      break;
    }
    case kDeleteCitizenRequest: {
      mutable_deletecitizenrequest()->::cmexample2domain::requestinterface::DeleteCitizenRequest::MergeFrom(from.deletecitizenrequest());
      break;
    }
    case kClearAllRequest: {
      mutable_clearallrequest()->::cmexample2domain::requestinterface::ClearAllRequest::MergeFrom(from.clearallrequest());
      break;
    }
    case READWRITEREQUEST_NOT_SET: {
      break;
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadWriteRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadWriteRequest::CopyFrom(const ReadWriteRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadWriteRequest::IsInitialized() const {

  return true;
}

void ReadWriteRequest::Swap(ReadWriteRequest* other) {
  if (other != this) {
    std::swap(readWriteRequest_, other->readWriteRequest_);
    std::swap(_oneof_case_[0], other->_oneof_case_[0]);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadWriteRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadWriteRequest_descriptor_;
  metadata.reflection = ReadWriteRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
