// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readresponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/readresponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadResponse_reflection_ = NULL;
struct ReadResponseOneofInstance {
  const ::cmexample2domain::requestinterface::ReadTownSummaryResponse* townsummary_;
  const ::cmexample2domain::requestinterface::ReadInfrastructureResponse* infrastructure_;
  const ::cmexample2domain::requestinterface::ReadCitizensResponse* citizens_;
}* ReadResponse_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/readresponse.proto");
  GOOGLE_CHECK(file != NULL);
  ReadResponse_descriptor_ = file->message_type(0);
  static const int ReadResponse_offsets_[4] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadResponse_default_oneof_instance_, townsummary_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadResponse_default_oneof_instance_, infrastructure_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(ReadResponse_default_oneof_instance_, citizens_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, readResponse_),
  };
  ReadResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadResponse_descriptor_,
      ReadResponse::default_instance_,
      ReadResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, _unknown_fields_),
      -1,
      ReadResponse_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadResponse, _oneof_case_[0]),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadResponse_descriptor_, &ReadResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto() {
  delete ReadResponse::default_instance_;
  delete ReadResponse_default_oneof_instance_;
  delete ReadResponse_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto();
  ::cmexample2domain::requestinterface::protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadcitizensresponse_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n=protobuf/cmexample2domain/requestinter"
    "face/readresponse.proto\022!cmexample2domai"
    "n.requestinterface\032Hprotobuf/cmexample2d"
    "omain/requestinterface/readtownsummaryre"
    "sponse.proto\032Kprotobuf/cmexample2domain/"
    "requestinterface/readinfrastructurerespo"
    "nse.proto\032Eprotobuf/cmexample2domain/req"
    "uestinterface/readcitizensresponse.proto"
    "\"\227\002\n\014ReadResponse\022Q\n\013townSummary\030\001 \001(\0132:"
    ".cmexample2domain.requestinterface.ReadT"
    "ownSummaryResponseH\000\022W\n\016infrastructure\030\002"
    " \001(\0132=.cmexample2domain.requestinterface"
    ".ReadInfrastructureResponseH\000\022K\n\010citizen"
    "s\030\003 \001(\01327.cmexample2domain.requestinterf"
    "ace.ReadCitizensResponseH\000B\016\n\014readRespon"
    "se", 602);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/readresponse.proto", &protobuf_RegisterTypes);
  ReadResponse::default_instance_ = new ReadResponse();
  ReadResponse_default_oneof_instance_ = new ReadResponseOneofInstance;
  ReadResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ReadResponse::kTownSummaryFieldNumber;
const int ReadResponse::kInfrastructureFieldNumber;
const int ReadResponse::kCitizensFieldNumber;
#endif  // !_MSC_VER

ReadResponse::ReadResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.ReadResponse)
}

void ReadResponse::InitAsDefaultInstance() {
  ReadResponse_default_oneof_instance_->townsummary_ = const_cast< ::cmexample2domain::requestinterface::ReadTownSummaryResponse*>(&::cmexample2domain::requestinterface::ReadTownSummaryResponse::default_instance());
  ReadResponse_default_oneof_instance_->infrastructure_ = const_cast< ::cmexample2domain::requestinterface::ReadInfrastructureResponse*>(&::cmexample2domain::requestinterface::ReadInfrastructureResponse::default_instance());
  ReadResponse_default_oneof_instance_->citizens_ = const_cast< ::cmexample2domain::requestinterface::ReadCitizensResponse*>(&::cmexample2domain::requestinterface::ReadCitizensResponse::default_instance());
}

ReadResponse::ReadResponse(const ReadResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.ReadResponse)
}

void ReadResponse::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_readResponse();
}

ReadResponse::~ReadResponse() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.ReadResponse)
  SharedDtor();
}

void ReadResponse::SharedDtor() {
  if (has_readResponse()) {
    clear_readResponse();
  }
  if (this != default_instance_) {
  }
}

void ReadResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadResponse_descriptor_;
}

const ReadResponse& ReadResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadresponse_2eproto();
  return *default_instance_;
}

ReadResponse* ReadResponse::default_instance_ = NULL;

ReadResponse* ReadResponse::New() const {
  return new ReadResponse;
}

void ReadResponse::clear_readResponse() {
  switch(readResponse_case()) {
    case kTownSummary: {
      delete readResponse_.townsummary_;
      break;
    }
    case kInfrastructure: {
      delete readResponse_.infrastructure_;
      break;
    }
    case kCitizens: {
      delete readResponse_.citizens_;
      break;
    }
    case READRESPONSE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = READRESPONSE_NOT_SET;
}


void ReadResponse::Clear() {
  clear_readResponse();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.ReadResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .cmexample2domain.requestinterface.ReadTownSummaryResponse townSummary = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_townsummary()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_infrastructure;
        break;
      }

      // optional .cmexample2domain.requestinterface.ReadInfrastructureResponse infrastructure = 2;
      case 2: {
        if (tag == 18) {
         parse_infrastructure:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_infrastructure()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_citizens;
        break;
      }

      // optional .cmexample2domain.requestinterface.ReadCitizensResponse citizens = 3;
      case 3: {
        if (tag == 26) {
         parse_citizens:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_citizens()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.ReadResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.ReadResponse)
  return false;
#undef DO_
}

void ReadResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.ReadResponse)
  // optional .cmexample2domain.requestinterface.ReadTownSummaryResponse townSummary = 1;
  if (has_townsummary()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->townsummary(), output);
  }

  // optional .cmexample2domain.requestinterface.ReadInfrastructureResponse infrastructure = 2;
  if (has_infrastructure()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->infrastructure(), output);
  }

  // optional .cmexample2domain.requestinterface.ReadCitizensResponse citizens = 3;
  if (has_citizens()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->citizens(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.ReadResponse)
}

::google::protobuf::uint8* ReadResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.ReadResponse)
  // optional .cmexample2domain.requestinterface.ReadTownSummaryResponse townSummary = 1;
  if (has_townsummary()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->townsummary(), target);
  }

  // optional .cmexample2domain.requestinterface.ReadInfrastructureResponse infrastructure = 2;
  if (has_infrastructure()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->infrastructure(), target);
  }

  // optional .cmexample2domain.requestinterface.ReadCitizensResponse citizens = 3;
  if (has_citizens()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->citizens(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.ReadResponse)
  return target;
}

int ReadResponse::ByteSize() const {
  int total_size = 0;

  switch (readResponse_case()) {
    // optional .cmexample2domain.requestinterface.ReadTownSummaryResponse townSummary = 1;
    case kTownSummary: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->townsummary());
      break;
    }
    // optional .cmexample2domain.requestinterface.ReadInfrastructureResponse infrastructure = 2;
    case kInfrastructure: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->infrastructure());
      break;
    }
    // optional .cmexample2domain.requestinterface.ReadCitizensResponse citizens = 3;
    case kCitizens: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->citizens());
      break;
    }
    case READRESPONSE_NOT_SET: {
      break;
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadResponse::MergeFrom(const ReadResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  switch (from.readResponse_case()) {
    case kTownSummary: {
      mutable_townsummary()->::cmexample2domain::requestinterface::ReadTownSummaryResponse::MergeFrom(from.townsummary());
      break;
    }
    case kInfrastructure: {
      mutable_infrastructure()->::cmexample2domain::requestinterface::ReadInfrastructureResponse::MergeFrom(from.infrastructure());
      break;
    }
    case kCitizens: {
      mutable_citizens()->::cmexample2domain::requestinterface::ReadCitizensResponse::MergeFrom(from.citizens());
      break;
    }
    case READRESPONSE_NOT_SET: {
      break;
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadResponse::CopyFrom(const ReadResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadResponse::IsInitialized() const {

  return true;
}

void ReadResponse::Swap(ReadResponse* other) {
  if (other != this) {
    std::swap(readResponse_, other->readResponse_);
    std::swap(_oneof_case_[0], other->_oneof_case_[0]);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadResponse_descriptor_;
  metadata.reflection = ReadResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
