// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readtownsummaryresponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/readtownsummaryresponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadTownSummaryResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadTownSummaryResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/readtownsummaryresponse.proto");
  GOOGLE_CHECK(file != NULL);
  ReadTownSummaryResponse_descriptor_ = file->message_type(0);
  static const int ReadTownSummaryResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadTownSummaryResponse, population_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadTownSummaryResponse, finance_),
  };
  ReadTownSummaryResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadTownSummaryResponse_descriptor_,
      ReadTownSummaryResponse::default_instance_,
      ReadTownSummaryResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadTownSummaryResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadTownSummaryResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadTownSummaryResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadTownSummaryResponse_descriptor_, &ReadTownSummaryResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto() {
  delete ReadTownSummaryResponse::default_instance_;
  delete ReadTownSummaryResponse_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nHprotobuf/cmexample2domain/requestinter"
    "face/readtownsummaryresponse.proto\022!cmex"
    "ample2domain.requestinterface\">\n\027ReadTow"
    "nSummaryResponse\022\022\n\npopulation\030\001 \001(\r\022\017\n\007"
    "finance\030\002 \001(\r", 173);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/readtownsummaryresponse.proto", &protobuf_RegisterTypes);
  ReadTownSummaryResponse::default_instance_ = new ReadTownSummaryResponse();
  ReadTownSummaryResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ReadTownSummaryResponse::kPopulationFieldNumber;
const int ReadTownSummaryResponse::kFinanceFieldNumber;
#endif  // !_MSC_VER

ReadTownSummaryResponse::ReadTownSummaryResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.ReadTownSummaryResponse)
}

void ReadTownSummaryResponse::InitAsDefaultInstance() {
}

ReadTownSummaryResponse::ReadTownSummaryResponse(const ReadTownSummaryResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.ReadTownSummaryResponse)
}

void ReadTownSummaryResponse::SharedCtor() {
  _cached_size_ = 0;
  population_ = 0u;
  finance_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReadTownSummaryResponse::~ReadTownSummaryResponse() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  SharedDtor();
}

void ReadTownSummaryResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReadTownSummaryResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadTownSummaryResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadTownSummaryResponse_descriptor_;
}

const ReadTownSummaryResponse& ReadTownSummaryResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadtownsummaryresponse_2eproto();
  return *default_instance_;
}

ReadTownSummaryResponse* ReadTownSummaryResponse::default_instance_ = NULL;

ReadTownSummaryResponse* ReadTownSummaryResponse::New() const {
  return new ReadTownSummaryResponse;
}

void ReadTownSummaryResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ReadTownSummaryResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(population_, finance_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadTownSummaryResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 population = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &population_)));
          set_has_population();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_finance;
        break;
      }

      // optional uint32 finance = 2;
      case 2: {
        if (tag == 16) {
         parse_finance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &finance_)));
          set_has_finance();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  return false;
#undef DO_
}

void ReadTownSummaryResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  // optional uint32 population = 1;
  if (has_population()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->population(), output);
  }

  // optional uint32 finance = 2;
  if (has_finance()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->finance(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.ReadTownSummaryResponse)
}

::google::protobuf::uint8* ReadTownSummaryResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  // optional uint32 population = 1;
  if (has_population()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->population(), target);
  }

  // optional uint32 finance = 2;
  if (has_finance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->finance(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.ReadTownSummaryResponse)
  return target;
}

int ReadTownSummaryResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 population = 1;
    if (has_population()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->population());
    }

    // optional uint32 finance = 2;
    if (has_finance()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->finance());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadTownSummaryResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadTownSummaryResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadTownSummaryResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadTownSummaryResponse::MergeFrom(const ReadTownSummaryResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_population()) {
      set_population(from.population());
    }
    if (from.has_finance()) {
      set_finance(from.finance());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadTownSummaryResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadTownSummaryResponse::CopyFrom(const ReadTownSummaryResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadTownSummaryResponse::IsInitialized() const {

  return true;
}

void ReadTownSummaryResponse::Swap(ReadTownSummaryResponse* other) {
  if (other != this) {
    std::swap(population_, other->population_);
    std::swap(finance_, other->finance_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadTownSummaryResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadTownSummaryResponse_descriptor_;
  metadata.reflection = ReadTownSummaryResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
