// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cmexample2domain/requestinterface/readinfrastructureresponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/cmexample2domain/requestinterface/readinfrastructureresponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cmexample2domain {
namespace requestinterface {

namespace {

const ::google::protobuf::Descriptor* ReadInfrastructureResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReadInfrastructureResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* BuildingInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BuildingInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto() {
  protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/cmexample2domain/requestinterface/readinfrastructureresponse.proto");
  GOOGLE_CHECK(file != NULL);
  ReadInfrastructureResponse_descriptor_ = file->message_type(0);
  static const int ReadInfrastructureResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadInfrastructureResponse, buildinginfo_),
  };
  ReadInfrastructureResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ReadInfrastructureResponse_descriptor_,
      ReadInfrastructureResponse::default_instance_,
      ReadInfrastructureResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadInfrastructureResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReadInfrastructureResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ReadInfrastructureResponse));
  BuildingInfo_descriptor_ = file->message_type(1);
  static const int BuildingInfo_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, opex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, freespaces_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, citizen_),
  };
  BuildingInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BuildingInfo_descriptor_,
      BuildingInfo::default_instance_,
      BuildingInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BuildingInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BuildingInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ReadInfrastructureResponse_descriptor_, &ReadInfrastructureResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BuildingInfo_descriptor_, &BuildingInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto() {
  delete ReadInfrastructureResponse::default_instance_;
  delete ReadInfrastructureResponse_reflection_;
  delete BuildingInfo::default_instance_;
  delete BuildingInfo_reflection_;
}

void protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nKprotobuf/cmexample2domain/requestinter"
    "face/readinfrastructureresponse.proto\022!c"
    "mexample2domain.requestinterface\"c\n\032Read"
    "InfrastructureResponse\022E\n\014buildingInfo\030\001"
    " \003(\0132/.cmexample2domain.requestinterface"
    ".BuildingInfo\"O\n\014BuildingInfo\022\014\n\004name\030\001 "
    "\001(\t\022\014\n\004opex\030\002 \001(\005\022\022\n\nfreeSpaces\030\003 \001(\005\022\017\n"
    "\007citizen\030\004 \003(\t", 294);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/cmexample2domain/requestinterface/readinfrastructureresponse.proto", &protobuf_RegisterTypes);
  ReadInfrastructureResponse::default_instance_ = new ReadInfrastructureResponse();
  BuildingInfo::default_instance_ = new BuildingInfo();
  ReadInfrastructureResponse::default_instance_->InitAsDefaultInstance();
  BuildingInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto {
  StaticDescriptorInitializer_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto() {
    protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto();
  }
} static_descriptor_initializer_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ReadInfrastructureResponse::kBuildingInfoFieldNumber;
#endif  // !_MSC_VER

ReadInfrastructureResponse::ReadInfrastructureResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.ReadInfrastructureResponse)
}

void ReadInfrastructureResponse::InitAsDefaultInstance() {
}

ReadInfrastructureResponse::ReadInfrastructureResponse(const ReadInfrastructureResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.ReadInfrastructureResponse)
}

void ReadInfrastructureResponse::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ReadInfrastructureResponse::~ReadInfrastructureResponse() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  SharedDtor();
}

void ReadInfrastructureResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReadInfrastructureResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReadInfrastructureResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReadInfrastructureResponse_descriptor_;
}

const ReadInfrastructureResponse& ReadInfrastructureResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto();
  return *default_instance_;
}

ReadInfrastructureResponse* ReadInfrastructureResponse::default_instance_ = NULL;

ReadInfrastructureResponse* ReadInfrastructureResponse::New() const {
  return new ReadInfrastructureResponse;
}

void ReadInfrastructureResponse::Clear() {
  buildinginfo_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ReadInfrastructureResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .cmexample2domain.requestinterface.BuildingInfo buildingInfo = 1;
      case 1: {
        if (tag == 10) {
         parse_buildingInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_buildinginfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_buildingInfo;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  return false;
#undef DO_
}

void ReadInfrastructureResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  // repeated .cmexample2domain.requestinterface.BuildingInfo buildingInfo = 1;
  for (int i = 0; i < this->buildinginfo_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->buildinginfo(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.ReadInfrastructureResponse)
}

::google::protobuf::uint8* ReadInfrastructureResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  // repeated .cmexample2domain.requestinterface.BuildingInfo buildingInfo = 1;
  for (int i = 0; i < this->buildinginfo_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->buildinginfo(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.ReadInfrastructureResponse)
  return target;
}

int ReadInfrastructureResponse::ByteSize() const {
  int total_size = 0;

  // repeated .cmexample2domain.requestinterface.BuildingInfo buildingInfo = 1;
  total_size += 1 * this->buildinginfo_size();
  for (int i = 0; i < this->buildinginfo_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->buildinginfo(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReadInfrastructureResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ReadInfrastructureResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ReadInfrastructureResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ReadInfrastructureResponse::MergeFrom(const ReadInfrastructureResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  buildinginfo_.MergeFrom(from.buildinginfo_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ReadInfrastructureResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadInfrastructureResponse::CopyFrom(const ReadInfrastructureResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadInfrastructureResponse::IsInitialized() const {

  return true;
}

void ReadInfrastructureResponse::Swap(ReadInfrastructureResponse* other) {
  if (other != this) {
    buildinginfo_.Swap(&other->buildinginfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ReadInfrastructureResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReadInfrastructureResponse_descriptor_;
  metadata.reflection = ReadInfrastructureResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int BuildingInfo::kNameFieldNumber;
const int BuildingInfo::kOpexFieldNumber;
const int BuildingInfo::kFreeSpacesFieldNumber;
const int BuildingInfo::kCitizenFieldNumber;
#endif  // !_MSC_VER

BuildingInfo::BuildingInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cmexample2domain.requestinterface.BuildingInfo)
}

void BuildingInfo::InitAsDefaultInstance() {
}

BuildingInfo::BuildingInfo(const BuildingInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cmexample2domain.requestinterface.BuildingInfo)
}

void BuildingInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opex_ = 0;
  freespaces_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BuildingInfo::~BuildingInfo() {
  // @@protoc_insertion_point(destructor:cmexample2domain.requestinterface.BuildingInfo)
  SharedDtor();
}

void BuildingInfo::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void BuildingInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BuildingInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BuildingInfo_descriptor_;
}

const BuildingInfo& BuildingInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fcmexample2domain_2frequestinterface_2freadinfrastructureresponse_2eproto();
  return *default_instance_;
}

BuildingInfo* BuildingInfo::default_instance_ = NULL;

BuildingInfo* BuildingInfo::New() const {
  return new BuildingInfo;
}

void BuildingInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<BuildingInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(opex_, freespaces_);
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  citizen_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BuildingInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cmexample2domain.requestinterface.BuildingInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_opex;
        break;
      }

      // optional int32 opex = 2;
      case 2: {
        if (tag == 16) {
         parse_opex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &opex_)));
          set_has_opex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_freeSpaces;
        break;
      }

      // optional int32 freeSpaces = 3;
      case 3: {
        if (tag == 24) {
         parse_freeSpaces:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &freespaces_)));
          set_has_freespaces();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_citizen;
        break;
      }

      // repeated string citizen = 4;
      case 4: {
        if (tag == 34) {
         parse_citizen:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_citizen()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->citizen(this->citizen_size() - 1).data(),
            this->citizen(this->citizen_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "citizen");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_citizen;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cmexample2domain.requestinterface.BuildingInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cmexample2domain.requestinterface.BuildingInfo)
  return false;
#undef DO_
}

void BuildingInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cmexample2domain.requestinterface.BuildingInfo)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 opex = 2;
  if (has_opex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->opex(), output);
  }

  // optional int32 freeSpaces = 3;
  if (has_freespaces()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->freespaces(), output);
  }

  // repeated string citizen = 4;
  for (int i = 0; i < this->citizen_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->citizen(i).data(), this->citizen(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "citizen");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->citizen(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cmexample2domain.requestinterface.BuildingInfo)
}

::google::protobuf::uint8* BuildingInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cmexample2domain.requestinterface.BuildingInfo)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 opex = 2;
  if (has_opex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->opex(), target);
  }

  // optional int32 freeSpaces = 3;
  if (has_freespaces()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->freespaces(), target);
  }

  // repeated string citizen = 4;
  for (int i = 0; i < this->citizen_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->citizen(i).data(), this->citizen(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "citizen");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->citizen(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cmexample2domain.requestinterface.BuildingInfo)
  return target;
}

int BuildingInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 opex = 2;
    if (has_opex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->opex());
    }

    // optional int32 freeSpaces = 3;
    if (has_freespaces()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->freespaces());
    }

  }
  // repeated string citizen = 4;
  total_size += 1 * this->citizen_size();
  for (int i = 0; i < this->citizen_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->citizen(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BuildingInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BuildingInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BuildingInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BuildingInfo::MergeFrom(const BuildingInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  citizen_.MergeFrom(from.citizen_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_opex()) {
      set_opex(from.opex());
    }
    if (from.has_freespaces()) {
      set_freespaces(from.freespaces());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BuildingInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BuildingInfo::CopyFrom(const BuildingInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BuildingInfo::IsInitialized() const {

  return true;
}

void BuildingInfo::Swap(BuildingInfo* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(opex_, other->opex_);
    std::swap(freespaces_, other->freespaces_);
    citizen_.Swap(&other->citizen_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BuildingInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BuildingInfo_descriptor_;
  metadata.reflection = BuildingInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace requestinterface
}  // namespace cmexample2domain

// @@protoc_insertion_point(global_scope)
